services:
  db:
  image: postgres:latest
  restart: always
  shm_size: 128mb
  environment:
    - POSTGRES_USER:$[DB_USER]
    - POSTGRES_PASSWORD:$[DB_PASSWORD]
    - POSTGRES_DB:$[DB_NAME)
  volumes:
    - './pg_data:/var/lib/postgresql/data'
  ports:
    - "5432:5432"
  app:
    build:
      context: .
    environment:
      NODE_ENV: production
      JWT_SECRET: $JWT_SECRET?
      JWT_EXPIRES: $fJWT_EXPIRES]
      DATABASE_URL: $[DATABASE_URL]
    depends_on:
      - db
    ports:
      - 3005:3005